name: Build, Compress and Release

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            python-version: "3.9"
            container: quay.io/pypa/manylinux2014_x86_64
          # - os: windows-latest
          #   python-version: "3.11"
          # - os: macos-latest
          #   python-version: "3.11"

    container: ${{ matrix.container || '' }}

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        if: ${{ !matrix.container }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python in container
        if: ${{ matrix.container }}
        run: |
          yum install -y python39 python39-devel python39-pip
          python3.9 -m pip install --upgrade pip
          alternatives --install /usr/bin/python python /usr/bin/python3.9 1

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build executable
        run: |
          pyinstaller --onefile simple_gui.py

      - name: Compress executable
        run: |
          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            powershell Compress-Archive -Path dist\* -DestinationPath dist\simple_gui_windows.zip
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            tar -czf dist/simple_gui_macos.tar.gz -C dist .
          else
            tar -czf dist/simple_gui_linux.tar.gz -C dist .
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-executable
          path: |
            dist/*.zip
            dist/*.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: ./artifacts/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
